### ISSUE TITLE
issue with location of new slots 

### ISSUE THREAD

**Issue by Thalanc** [shudnal/ExtraSlots#10]
i just loaded extraslots and the menu looks like this ? What is wrong how to correct it .. i have V+ and set the player inventory slots to vanilla, have adjusted the chest slots fyi.
I have this mod on a local game and it worked fine with V+, this pic is from a dedicated server where it didnt work, i have noticed a few things act differently on dedicated servers ...seems odd. 
![Extraslots image](https://github.com/user-attachments/assets/c4a225a6-84b6-41fc-9018-f2dd4bd3d30a)
thanks for any help you can provide
Thalanc (Andrew)

**Comment by Thalanc** [comment]
![Extraslots image local game](https://github.com/user-attachments/assets/e0143595-c259-4327-bf56-8aa8c7e82316)
here is the local game the same mods (actually a lot more in this test game) in a V+ game ... just an added thought how do I move the SRQ down a bit to get rid of the overlap

**Comment by shudnal** [comment]
It seems you have config loaded from server where inventory section is enabled. While your local config works well and you have this section disabled.

**Comment by shudnal** [comment]
If it's not the case and both server and client configuration both have inventory section disabled then reopen the issue and I'll check it.

**Comment by Thalanc** [comment]
> If it's not the case and both server and client configuration both have inventory section disabled then reopen the issue and I'll check it.

In both situations V+ has inventory enabled .. so thats what confused me works fine local not on the server??

**Comment by shudnal** [comment]
I'll check if that is some Valheim+ thing because besides that there should be no difference for this mod where only server related thing is config synchronization.

**Comment by Thalanc** [comment]
there are only 2 of us on my dedicated server ... it doesnt have yoru mod in the lsit so we are only running them client side .. i saw you did an update .. doubt it was for this but its the same ( thought I would see) 

![valhost](https://github.com/user-attachments/assets/a9fb625c-d8f2-43ba-9167-6581ef79817c)
