### ISSUE TITLE
re-open extraslot question

### ISSUE THREAD

**Issue by Thalanc** [shudnal/ExtraSlots#11]

**Comment by Thalanc** [comment]
In both situations V+ has inventory enabled .. so thats what confused me works fine local not on the server??

**Comment by Thalanc** [comment]
i would disable inventory however 1) I like getting the extra invetory slots for the polayer just 1 or 2 rows 2) its a pain to make all my chests smaller need to unload and rebalance them all or lose inventory

**Comment by shudnal** [comment]
Both [Custom Container Sizes](https://www.nexusmods.com/valheim/mods/111) from aedenthorn (not from link but [fixed](https://www.nexusmods.com/valheim/mods/2798) version) and [AzuContainerSizes](https://thunderstore.io/c/valheim/p/Azumatt/AzuContainerSizes/) could be used for container resize.
ExtraSlots can add up to 5 extra rows of regular player inventory.

**Comment by Thalanc** [comment]
ok thanks ... i was looking through yor mod .. where do you add the player inventory rows? didnt see a clear label thanks appreciate the quick replies 
why did it work on the local version with V+ and not the server?

**Comment by shudnal** [comment]
**Amount of extra inventory rows** config in main **Extra Slots** section. I'll check how it works on dedicated server but if you disable Valhem+ **Inventory** section and replace it with other mods it should work. There was similar issue on the Nexus and it workd for them.

**Comment by Thalanc** [comment]
Hi Shudnal - thanks for the info .. AzucontainerSize worked... converted containers.. found the inventory extra row section and disabled invetory in V+ now the server game works perfectlya nd I didnt lose any inventory .. appreciate the hlep and patience helping me unbderstand and solve it .. great mod will use this in all my games .. do you have a donation link?
thanks
Thalanc

**Comment by Thalanc** [comment]
another question .. is there a way to make the quick slots not show below the character ?

**Comment by shudnal** [comment]
**Panels - Ammo slots** and **Panels - Quick slots** config sections have config **Enabled** which control if hotbar should be enabled for given slots.
