### ISSUE TITLE
sorts and puts the item in boxes

### ISSUE THREAD

**Issue by nlineprime** [shudnal/ExtraSlots#13]
Your slots are sorted and stashing in storage with this mod. He drops them into his inventory and sorts them
https://thunderstore.io/c/valheim/p/Goldenrevolver/Quick_Stack_Store_Sort_Trash_Restock/
pls fix or add lock this slots. 
other slot mods fix them and they are not subject to sorting by this mod, but I want to use your mod in it for more functions that I need

**Comment by shudnal** [comment]
That's not to do on my side. GoldenRevolver is aware of the issue since version 1.0.0 and it should be done on their side.

For now as a workaround you can mark this extra slots as favourite and it will not be moved on sorting.

**Comment by nlineprime** [comment]
ok thanks i try

**Comment by shudnal** [comment]
Compatibility provided in 1.0.15.
