### ISSUE TITLE
0.218.21 Ashlands: default_prebw

### ISSUE THREAD

**Issue by BETLOG** [shudnal/ExtraSlots#14]
Would you be prepared to adapt these two companion mods to the pre-bogwitch stable valheim release?
ie: 0.218.21 Ashlands (default_prebw in steam betas)

**Comment by BETLOG** [comment]
> [ExtraSlots.zip](https://github.com/user-attachments/files/17904445/ExtraSlots.zip)

Thanks.
Can you also supply the companion-revision for https://github.com/shudnal/ExtraSlotsCustomSlots

**Comment by shudnal** [comment]
It should work.

**Comment by BETLOG** [comment]
It could be some other unrelated mod conflict, but the only backpack/slots mods i have active right now is adventurebackpacks .... so I'm just going to go with "nope, mod versions above are not default-prebw compatible"
Thanks anyway.

Now if irongate would just fix the movement freezing issues their gamepad revisions introduced to bogwitch, i'd be able to use this mod.
![2024-11-27--15-22-24_betlogbeast_1920x1080+0+0](https://github.com/user-attachments/assets/d4e1b474-5c66-4f54-b5b1-7052dd978bb2)

**Comment by shudnal** [comment]
If crafting window looks like that it means you must have an error in log file. This error prevents hud from initializing.
I've tested [ExtraSlots.zip](https://github.com/user-attachments/files/17935406/ExtraSlots.zip) on 0.218.21 without AdventureBackpacks and it works. 
![image](https://github.com/user-attachments/assets/5bbda46c-d263-46e7-8040-9f0245095857)

**Comment by shudnal** [comment]
AdventureBackpacks 1.7.6 works as well.
![image](https://github.com/user-attachments/assets/5722cdf1-4a9a-47a3-8526-c253dd4b5401)

**Comment by BETLOG** [comment]
> I've tested [ExtraSlots.zip](https://github.com/user-attachments/files/17935406/ExtraSlots.zip) on 0.218.21

Ok, that zip works better.
The manifest in the above zip says its 1.0.12 but the actual content of the zip differs from thunderstore 1.0.12
I only point this out because it would be good to know for future reference which thunderstore version you got to work.
![2024-11-29--11-56-49_betlogbeast_ExtraSlotszipArk](https://github.com/user-attachments/assets/1962d5af-e100-4562-8869-7e23df1b1988)

Some observations:
Using [the most recently linked ](https://github.com/user-attachments/files/17935406/ExtraSlots.zip) and shudnal-ExtraSlotsCustomSlots-1.0.4
devcommands
nocost
itemset mistlands
spawn wishbone
spawn cryptkey
spawn beltstrength
xb:version 

1) when i right click on wishbone in inv it says its active, but vanishes. Not evident in extraslots.
![2024-11-29--12-12-48_betlogbeast_1920x1080+0+0](https://github.com/user-attachments/assets/98e4ffe0-1461-4770-b0aa-062546a74096)
But after stepping away from workbench i had been interacting with and spawning another wishbone, the prior one now appears in extraslots
... just brainfarting what im seeing here, i know interacting with a workbench and activating the wishbone probably isnt 'normal' procedure, and that this reversion version matching may be weird.
2) apparently I can use more than one wishbone at once. Is there an additional effect/range? i'm thinking its unintended.
![2024-11-29--12-18-26_betlogbeast_1920x1080+0+0](https://github.com/user-attachments/assets/44bfdfd2-8367-4bd5-9ca5-68194646e9f7)
3) cryptkey has to be drag&dropped into a slot, cannot be right clicked. No problem, just slightly inconsistent.
4) I have shudnal-CircletExtended-1.0.11 active, but helm and circlet cannot be worn at same time... iirc i am able to do this in my normal Azumatt-AzuExtendedPlayerInventory-1.4.3 setup.
Circlet cannot be dragged into circlet extraslot.
![2024-11-29--12-31-51_betlogbeast_1920x1080+0+0](https://github.com/user-attachments/assets/dda8def4-c5e3-4748-833e-caddca06c4de)
5) Smoothbrain backpacks (default and yml custom) are functional. But ['place stacks](https://github.com/blaxxun-boop/Backpacks/issues/59)' still doesnt work - nice transparent mod passthrough, but i was almost daring to hope you'd fixed it :}
6) I'm not seeing quickslot 4-6. I have: quickslots slider = 6, slots progression = disabled, not sure what other settings are relevant, if any.

**Comment by shudnal** [comment]
Archives contais different dll because it's compiled against diferent game version and have changes in code. It is put into archive for more convenient use in mod manager. This PreBW version is also uploaded on [Nexus](https://www.nexusmods.com/valheim/mods/2901?tab=files)

1. It should appear in slot after you close and open inventory again. I'll check if it is reproducable in live version.
2. By defaylt there is no limitation of which utility items you want to use. It simply doesn't work if you equip multiple similar vanilla items.
3. Cryptkey is not intended to be rightclicked to put into slot.
4. Circlet requires lvl2 to be equipped into circlet slot. Circlet lvl1 works as regular helmet.
5. ExtraSlots doesn't change place stacks feature so I have no idea how I can help.

**Comment by BETLOG** [comment]
Question: I'm unclear on how to add the prebw version to a modpack. Is this going to be sufficient?
```
"dependencies": [
 ...
 `"ExtraSlots-PreBW.zip-2901-1-0-13-1732984058",`
...
]
```

**Comment by shudnal** [comment]
I have no idea as I didn't do modpacks yet but it doesn't look right. In my understanding **dependencies** field should contain identifiers of published mods. IIRC you can just add local mod in modpack archive itself.

**Comment by BETLOG** [comment]
> I have no idea as I didn't do modpacks yet but it doesn't look right. In my understanding **dependencies** field should contain identifiers of published mods.

Correct.
But the unique identifier on thunderstore is the name of the file, and subsequently the directory it gets unzipped to.
eg:
```
{
    "name": "TestMod",
    "version_number": "1.1.0",
    "website_url": "https://github.com/thunderstore-io",
    "description": "This is a description for a mod. 250 characters max",
    "dependencies": [
        "shudnal-CircletExtended-1.0.11",
        "shudnal-ConfigurationManager-1.0.17",
        "shudnal-HarpoonExtended-1.1.10",
        "shudnal-LongshipUpgrades-1.0.1"
    ]
}
```
so presumably 
       "ExtraSlots-PreBW.zip-2901-1-0-13-1732984058",
is also correct.... i'll try that, but in case i cant.....

> IIRC you can just add local mod in modpack archive itself.

Please confirm that I have your permission to include the contents of https://www.nexusmods.com/valheim/mods/2901?tab=files&file_id=18282 in modpacks.

**Comment by shudnal** [comment]
Well as stated at Nexus you can do whatever you want with files.
