### ISSUE TITLE
Error when selecting server to join game (non-game breaking)

### ISSUE THREAD

**Issue by Karmacopper** [shudnal/ExtraSlots#15]
Getting the following error in the BepinEx console:

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ExtraSlots.EquipmentPanel+RectTransformUtility_RectangleContainsScreenPoint_BackpacksCompat.Postfix (UnityEngine.RectTransform rect, UnityEngine.Vector2 screenPoint, System.Boolean& __result) (at <4b9e4846cf0e475db52266a4743f303d>:0)
(wrapper dynamic-method) UnityEngine.RectTransformUtility.DMD<UnityEngine.RectTransformUtility::RectangleContainsScreenPoint>(UnityEngine.RectTransform,UnityEngine.Vector2)
(wrapper dynamic-method) UITooltip.DMD<UITooltip::LateUpdate>(UITooltip)

This is client-side, mod not installed on server.

**Comment by shudnal** [comment]
Fixed in 1.0.11.
