### ISSUE TITLE
ExtraSlots - enhancement suggestion: foodslots

### ISSUE THREAD

**Issue by BETLOG** [shudnal/ExtraSlots#17]
either:
a) Replace the vertical food expiry bar with a 3-6 quickslot bar, so users only need the one interface to see what foods are expiring and also to load those foods into for use with a hotkey.
or:
b) put another hotkeyable bar next to the vertical food expiry bar, so users can hotkey select from 3-6 different quickslots to eat from.
eg: 
![2024-11-29--13-52-30_betlogbeast_20241129135124betlogbeastSteamimported10RGBcolor8bitgammaintegerGIMPbuiltinsRGB2layers439x306GIMP](https://github.com/user-attachments/assets/b9e85ae5-2577-4548-9a59-11bbc5b1f76b)

**Comment by shudnal** [comment]
There will be no food hotbar ever. You use food only once per 10-15 minute at max. You don't use food reactively. There is absolutely no need to clutter UI even more adding this redundant food hotbar.
