### ISSUE TITLE
ExtraSlots feature suggestion: stacked quickslots

### ISSUE THREAD

**Issue by BETLOG** [shudnal/ExtraSlots#18]
The option to stack quickslots in 2 rows of 3 columns would be great.
- inventory area: It may not work so well as it might cover the inworld screen too much for some people
- Screen hud area: seems like an improvement. I don't think it interferes with anything else too badly.
![2024-11-29--13-56-19_betlogbeast_20241129135124betlogbeastSteamimported10RGBcolor8bitgammaintegerGIMPbuiltinsRGB8layers439x306GIMP](https://github.com/user-attachments/assets/a9bce27d-2e35-4609-a326-d60472b5b9f1)

**Comment by shudnal** [comment]
That's actually a great idea to make it look like screenshot. Looks pretty easy to implement so most likely it will be done in the next version. But quick slots position on equipment panel will be as it is now.

**Comment by shudnal** [comment]
In 1.0.13 you can make it look whatever you want. Both ammo and quick slots. Even make it vertical.

**Comment by BETLOG** [comment]
Very nice, but  unless 1.0.13 works in default_prebw I still need Valheim to fix the keyboard/mouse stuff their gamepad improvements broke for me in bogwitch.
So the revision is excellent news, but I can't try it yet :)

**Comment by shudnal** [comment]
I've updated preBW version as well. https://www.nexusmods.com/valheim/mods/2901?tab=files

**Comment by BETLOG** [comment]
Oh wow, thanks.
Someone actually facilitating my use of an old version of a game... that never happens. 

>1.0.12

1.0.3-preBW probably would have been more [Semantic Versioning 2.0.0](https://semver.org/#spec-item-10) compliant ]:)
1.-1.3-preBW probably even more so, except for the negative sign

**Comment by BETLOG** [comment]
Is there any version correlation between nexus and thunderstore? I was learning how to make modpacks last night, and wonder how to include this regression-revision in one of those.

**Comment by BETLOG** [comment]
re 1.0.12
`Hide stack size in hotbar` - seems to have no effect
`ammo slots`: i see there is only 3, even with all progression disabled. Presumably this is an indexing and compatibility limitation. Would it be possible to increase ammo slots if there were a lower value of utility item slots, or similar slot reduction elsewhere? Or allow ammo to be also selected in quickslots?

**Comment by shudnal** [comment]
You can use preBW version from Nexus as a local mod as it is already compatible zip. That's the best I can do.

Version name was not changed for consistency. If you use preBW server and mod works you know what is the actual version.

Hide stacks feature works only for usable or consumable items like meads and ammo. It's stated in tooltip.

There is no limitation on ammo in quick slots or anywhere else. This 3 ammo slots is only for convenient hotbar usage.
BBH works as intended. You can change shortcuts and use both mods ammo slots if you want. Of left just BBH quiver, it's up to you.

Limitation of 3 ammo slots is more for better looking equipment panel layout. And in general 3 slots should be well enough. You rarely use more than 3 arrow types in a fight.

**Comment by BETLOG** [comment]
>and use both mods ammo slots if you want

Yeah, i think the overlap of options was confusing me.
Also I could not successfully bind a modifier key and a key already in use. eg: can bind LShift+1, but it doesnt select ammo reliably or at all, and always triggers weapon slot 1 -  using BBH single modifier key solves this problem for me though.

> You rarely use more than 3 arrow types in a fight.

Yeah, but we rarely use 8 weapon slots in a fight either. Wanting ~3-6 arrow slots is more about visual inventory and ease of selection as per the vanilla 1-8 quickkeys - less juggling, or needing to forsee and pre-prepare.
But again: BBH solves this for me.

Thanks for the consideration anyway.
