### ISSUE TITLE
unable to use modifier key+already bound key

### ISSUE THREAD

**Issue by BETLOG** [shudnal/ExtraSlots#19]
1.0.12 prebw
The keys bound +LShift do not register as the correct slot, rather they trigger the key sans modifier key
ie: press: Lshift+[  = just triggers [ action

![2024-12-01--18-24-37_betlogbeast_Valheim](https://github.com/user-attachments/assets/a4948970-1bc7-478b-a54f-dc58cbdfbd53)

**Comment by shudnal** [comment]
Vanilla hotkey prevention doesn't work in PreBW version. There was major changes in input system. It have to be done from scratch and I don't have enough motivation for it.
