### ISSUE TITLE
How to Setup like in your Screenshot?

### ISSUE THREAD

**Issue by MisterMatters** [shudnal/ExtraSlots#2]
for some reason i cant get it to look like in your Screenshot

first 3 Quick Slots not shown last 3 are overlapped

Chest cant be located in middle leftside like you have it in the screenshot 

Ammo slots are not even shown :( Is it a resolution thing? As i am useing a 1440 Screen?

![image](https://github.com/user-attachments/assets/c3b8b3a1-121a-4f26-8d95-97309f6082df)

**Comment by shudnal** [comment]
It looks like mod adding this new buttons changes something inventory related. What is this mod? I need to check to provide compatibility if possible.

**Comment by shudnal** [comment]
I've found the [mod](https://thunderstore.io/c/valheim/p/Goldenrevolver/Quick_Stack_Store_Sort_Trash_Restock/) and already asked the author to provide compatibility. Yet it should not cause the issue you experience.
Do you have any error in log file? What mods are you using? It seems there could be some incompatibility.

**Comment by shudnal** [comment]
And some minor thing. By default Slot Progression is enabled. It means you will get more slots when your character or world meet certain criteria set in config values. If you want all slots available without conditions you should disable Slot Progression config value.

**Comment by shudnal** [comment]
There was some changes in 1.0.4 pls check if it's better now. 
Outside of Goldenrevolver-Quick_Stack_Store_Sort_Trash_Restock-1.4.11 I see no potential issues which can cause inventory to look like that.

**Comment by MisterMatters** [comment]
hmm still mess on "main Char: 
![image](https://github.com/user-attachments/assets/c76850c8-b47f-4741-b042-29eba19b2926)

but it could be my own fault Mod needs to be installed Server side too right?!

**Comment by shudnal** [comment]
Well I have no idea what can go wrong if you didn't have it on the server. In theory the only thing server should handle in that case is config synchronisation. Totally worth the try to install it on the server.

**Comment by shudnal** [comment]
And try to disable Sort mod. It does have incompatibility rn.

**Comment by shudnal** [comment]
I've checked with 

rendl0449-CraftFromContainers-3.5.7
Grantapher-ValheimPlus_Grantapher_Temporary-9.15.0
mtnewton-Gravekeeper-2.2.0
Goldenrevolver-Quick_Stack_Store_Sort_Trash_Restock-1.4.11
MSchmoecker-MultiUserChest-0.6.0
ishid4-BetterArchery-1.9.8

all of them was simultaneously installed and it works.

In 1.0.5 there is better Valheim Plus compat. Pls check if it helps. If the issue still exists pls find the mod causing this by disabling mods one by one and reopen the issue.

**Comment by MisterMatters** [comment]
Thanks for trying to help, seems like it is just not working for me.

I disabled Store mod it looked ok relogged still disabled and messed up again
i disabled Better Archery and put Store back on logged in all good relog again messed up.

guess i can't get your mod to work. Maybe it is compatible some day.

ill stay tuned!
