### ISSUE TITLE
question: possible to add VDS_AtlantianCrown/several helms

### ISSUE THREAD

**Issue by BETLOG** [shudnal/ExtraSlots#20]
VikingsDoSwim 1.3.4 adds item called VDS_AtlantianCrown, it has no on-off toggle but rather is activated by wearting.
Would it be possible to allow i to be stored and worn/unworn in an extraslots slot?
Similarly; would it be possible to extend customslots add slots for the several hems that we often find ourselves carrying (metal for fights, root helm for poison) so they are separate from main inventory, and can be worn/unworn from the extraslots panel?
![2024-12-01--18-35-53_betlogbeast_Valheim](https://github.com/user-attachments/assets/ccb0ffbd-4d3d-49a5-9c6c-a668e69c9edf)

**Comment by shudnal** [comment]
Making an item fit into its own slot is quite tricky, and also depends on the implementation and logic of the item's effects. Ideally, this should be done by the mod author, and if not, it should be considered part of the mod's design.

Also, in your particular case, changing helmets depending on the situation is part of inventory/equipment management.
