### ISSUE TITLE
extra slots/betterArchery

### ISSUE THREAD

**Issue by Emppuuh** [shudnal/ExtraSlots#21]
So i got this warning, is this mod broken or should it work?

[Warning:Extra Slots] BetterArchery's Quiver was disabled to prevent issues with inventory grid. You will not lose arrows if you had Quiver enabled in your previous session.
This logic is designed for BetterArchery version 1.9.8, current version is 1.9.8. If quiver implementation was changed pls contact me at any platform.

**Comment by shudnal** [comment]
Well as it is already stated: quiver was disabled and you will not lose your arrows. I don't think I can add anything to this. Quiver implementation is not compatible but the rest of the mod is fine.
