### ISSUE TITLE
Need Feature

### ISSUE THREAD

**Issue by serjgorelikoff** [shudnal/ExtraSlots#22]
This is not a bug, this is a wish. I use the Quick_Stack_Store_Sort_Trash_Restock mod from Goldenrevolver. When sorting, the slots are also sorted with the entire inventory. Is there any way to fix this behavior?

**Comment by shudnal** [comment]
Compatibility with Quick_Stack_Store_Sort_Trash_Restock was provided in 1.0.15. Are you sure you use that version? I can't reproduce the issue.

**Comment by serjgorelikoff** [comment]
I apologize for not following the update.
