### ISSUE TITLE
config issue

### ISSUE THREAD

**Issue by Thalanc** [shudnal/ExtraSlots#23]
after the latest update the confgi file ( opened in R2Modman ) is odd and not editable?
waht happened any idea how to fix it?
![Screenshot 2024-12-18 config edit](https://github.com/user-attachments/assets/fcc3aaf0-15f9-4e5c-ade3-cdfb0402c4ca)

**Comment by shudnal** [comment]
File you showing is `Extra Slots.English.json` which is localization example file overwrited on every update.
