### ISSUE TITLE
Unique utility item settings don't work for Jewelcrafting Rings

### ISSUE THREAD

**Issue by frivolour** [shudnal/ExtraSlots#6]
Hi, I'm trying to set Jewelcrafting rings and Wizardry rings to be mutual exclusive, such that you can only equip one at a time.
I have added the following to my unique utility items config:

`$ring_blackforest_TW:$jc_ring_red`

However, I can still equip the two rings simultaneously.
This made me thing I was getting the names wrong, but looking at your [code](https://github.com/shudnal/ExtraSlots/blob/master/ExtraUtilitySlots.cs#L76) it seems that you are using `m_name`. I checked the `m_name` of both items using `wackydb_save_item` and those are indeed their m_names.

I have been able to successfully get Wizardry rings to be mutually exclusive, e.g

`$ring_blackforest_TW:$ring_plains_TW:$ring_mountain_TW`

But for Jewelcrafting rings I've had no luck. Not sure if I'm missing something?

**Comment by shudnal** [comment]
Glad you've figured it out!
