### ISSUE TITLE
Player can equip more than 5 utility items.

### ISSUE THREAD

**Issue by sighsorry1029** [shudnal/ExtraSlots#7]
![Screenshot 2024-11-18 155538](https://github.com/user-attachments/assets/d44bce48-a609-4dc2-b0b3-9fd5c4f13c8a)

Hello, I have recently tried extra slots and it looks like player can wear more than 5 utility item. I have tried with mods that adds utiility items like Jewelcrafting and MagicPlugin and player can equip  utility items right on inventory(not replacing the utility slot that is full)

**Comment by shudnal** [comment]
Well this mod can't handle more than 4 extra utility slots. +1 utility comes with vanilla utility slot. Are you sure this extra items work and not just have visual cue? Do this extra items have "utility" item type or maybe it is handled by some other mod?

**Comment by shudnal** [comment]
![image](https://github.com/user-attachments/assets/f89c2d7a-1a1d-45d0-816e-d99c676fdadd)
Without ExtraSlots I was able to equip ring, neckace and utility at the same time. I guess necklace and ring slots are JC thing.

**Comment by sighsorry1029** [comment]
> So in your case you have 5 regular utility slots + necklace slot + ring slot.

Now everything got clear. Thank you for the reply!
